Repository IBM/ibm-healthcheck-operator, pull requests merged in 2020-09, with the labels that each got.

#81 bump up version to 3.7.1
  .gitignore
  .osdk-scorecard.yaml
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/ibm-healthcheck-operator.v3.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#83 update digest
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/ibm-healthcheck-operator.v3.7.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#82 update go modules
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#84 update labels to fix cv-lint issues
  deploy/crds/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/crds/operator.ibm.com_healthservices_crd.yaml
  deploy/crds/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/crds/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/crds/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherjob_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/ibm-healthcheck-operator.v3.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/L

#85 update operator.yaml to pass cv lint
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#86 update service account
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherconfig_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherjob_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/ibm-healthcheck-operator.v3.7.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#88 Update operand image digest
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.1/ibm-healthcheck-operator.v3.7.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#89 bump version to 3.7.2
  .osdk-scorecard.yaml
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/ibm-healthcheck-operator.v3.7.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#90 update operand digest
  common/scripts/update-digest.sh
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/ibm-healthcheck-operator.v3.7.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#91 update operand digest
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.2/ibm-healthcheck-operator.v3.7.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#92 update crds
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/mustgatherservice/mustgatherservice.go
  pkg/controller/mustgatherservice/mustgatherservice_controller.go
Labels: approved, lgtm, size/L

#93 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#94 add logic to update configmap
  pkg/controller/mustgatherconfig/mustgatherconfig_controller.go
Labels: approved, lgtm, size/S
