Repository IBM/ibm-healthcheck-operator, pull requests merged in 2020-04, with the labels that each got.

#29 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/M

#31 seperate image and repo
  deploy/crds/operator.ibm.com_healthservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.0/ibm-healthcheck-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.0/operator.ibm.com_healthservices_crd.yaml
  pkg/apis/operator/v1alpha1/healthservice_types.go
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
Labels: approved, lgtm, size/M

#32 imageRegistry
  deploy/crds/operator.ibm.com_healthservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.0/ibm-healthcheck-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  pkg/apis/operator/v1alpha1/healthservice_types.go
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
Labels: approved, lgtm, size/M

#33 update to 3.6.0
  version/version.go
Labels: approved, lgtm, size/XS
