Repository IBM/ibm-healthcheck-operator, pull requests merged in 2020-07, with the labels that each got.

#55 expose CR resources
  deploy/crds/operator.ibm.com_healthservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/ibm-healthcheck-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/operator.ibm.com_healthservices_crd.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/healthservice_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
  pkg/controller/healthservice/resources.go
Labels: approved, lgtm, size/XL

#57 add must-gather service
  deploy/crds/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/ibm-healthcheck-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  pkg/apis/operator/v1alpha1/mustgatherservice_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_mustgatherservice.go
  pkg/controller/mustgatherservice/mustgatherservice_controller.go
Labels: approved, lgtm, size/XL

#58 add must-gather job
  deploy/crds/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherjob_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/ibm-healthcheck-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/healthservice_types.go
  pkg/apis/operator/v1alpha1/mustgatherjob_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_mustgatherjob.go
  pkg/controller/mustgatherjob/mustgatherjob_controller.go
Labels: approved, lgtm, size/XL

#56 Br expose cr resources - add replicas field
  deploy/crds/operator.ibm.com_healthservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/ibm-healthcheck-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/operator.ibm.com_healthservices_crd.yaml
  pkg/apis/operator/v1alpha1/healthservice_types.go
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
  pkg/controller/healthservice/resources.go
Labels: approved, lgtm, size/L

#60 update csv example
  deploy/crds/operator.ibm.com_healthservices_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherconfig_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/ibm-healthcheck-operator.v3.7.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#62 add labels
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
  pkg/controller/mustgatherconfig/mustgatherconfig_controller.go
  pkg/controller/mustgatherjob/mustgatherjob_controller.go
  pkg/controller/mustgatherservice/mustgatherservice_controller.go
Labels: approved, lgtm, size/M

#61 CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#63 update image struct
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/healthservice_types.go
  pkg/apis/operator/v1alpha1/mustgatherjob_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S
