Repository IBM/ibm-healthcheck-operator, pull requests merged in 2020-06, with the labels that each got.

#44 support mutilarch image
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/L

#45 bump csv and operator version to 3.6.1
  .osdk-scorecard.yaml
  README.md
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.1/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.1/ibm-healthcheck-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.1/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#46 increase resource limits for power
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.1/ibm-healthcheck-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
Labels: approved, lgtm, size/S

#47 no date in image tag
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/XS

#48 update image VERSION in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#49 add beta channel with csv version 3.6.1
  deploy/olm-catalog/ibm-healthcheck-operator/3.6.1/ibm-healthcheck-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
Labels: approved, lgtm, size/XS

#50 push stable-v1 channel with csv version 3.6.1
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
Labels: approved, lgtm, size/XS

#52 update base image
  build/Dockerfile
Labels: approved, lgtm, size/XS

#53 Feature/protect csv
  Makefile
  common/scripts/.githooks/pre-commit
  common/scripts/protect-csv.sh
  common/scripts/push-csv.sh
Labels: approved, lgtm, size/L

#54 add feature bump up csv
  .gitignore
  .osdk-scorecard.yaml
  Makefile
  common/scripts/bump-up-csv.sh
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/ibm-healthcheck-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.7.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/XXL
