Repository IBM/ibm-healthcheck-operator, pull requests merged in 2020-10, with the labels that each got.

#96 bump up version to 3.8.0
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_v1alpha1_healthservice_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_mustgatherservice_cr.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/ibm-healthcheck-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  pkg/controller/healthservice/memcached.go
  version/version.go
Labels: approved, lgtm, size/XXL

#97 reduce must-gather cluster permission
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/ibm-healthcheck-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#98 reduce healthcheck permission
  README.md
  common/scripts/update-digest.sh
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.0/ibm-healthcheck-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/healthservice/healthservice.go
Labels: approved, lgtm, size/M
