Repository IBM/ibm-healthcheck-operator, pull requests merged in 2021-07, with the labels that each got.

#143 Must gather version bump up to 4.5.7
  deploy/olm-catalog/ibm-healthcheck-operator/3.11.0/ibm-healthcheck-operator.v3.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#144 Operand version bumpup for ubi image update
  deploy/olm-catalog/ibm-healthcheck-operator/3.11.0/ibm-healthcheck-operator.v3.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#145 Changes for license management Epic:48221
  deploy/olm-catalog/ibm-healthcheck-operator/3.11.0/ibm-healthcheck-operator.v3.11.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#146 Bumpup operator version for 3.10.0
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/ibm-healthcheck-operator.v3.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL

#147 Removed deprecated ingress api to adapt networking/v1
  cmd/manager/main.go
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/ibm-healthcheck-operator.v3.12.0.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/controller/constant/constants.go
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/healthservice_controller.go
  pkg/controller/mustgatherservice/mustgatherservice.go
Labels: approved, lgtm, size/XL

#148 Updated must-gather-svc ing reconcile logic
  pkg/controller/mustgatherservice/mustgatherservice_controller.go
Labels: approved, lgtm, size/S

#150 Update latest operands for 3.10.0 change
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/ibm-healthcheck-operator.v3.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#149 Changes for 48314:set imagePullPolicy to IfNotPresent
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/ibm-healthcheck-operator.v3.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#151 Modifying ubi image tag to remediate Twistlock scan issue: 48424
  build/Dockerfile
Labels: approved, size/XS
