Repository IBM/ibm-healthcheck-operator, pull requests merged in 2021-08, with the labels that each got.

#152 Enable UBI Automation for heathcheck operator
  base-images.json
  build/Dockerfile
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/XS

#154 Updated fix for lint issue CSVHasValidRelatedImages
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/ibm-healthcheck-operator.v3.12.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#155 Updated operator image
  deploy/olm-catalog/ibm-healthcheck-operator/3.12.0/ibm-healthcheck-operator.v3.12.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#153 Add docker labels for VCS_REF and VCS_URL [Do Not Merge]
  Makefile
Labels: approved, lgtm, size/XS

#157 Fix for prow build failure
  Makefile
Labels: approved, lgtm, size/XS

#158 Go version update(v1.16.7) for PSIRT fixes
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#159 fix lint errors
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/ibm-healthcheck-operator.v3.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_mustgatherservices_crd.yaml
Labels: approved, lgtm, size/M

#160 fix permission for ingress api
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/ibm-healthcheck-operator.v3.13.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#161 Update CRD for 3.13.0
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/ibm-healthcheck-operator.v3.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.13.0/operator.ibm.com_mustgatherservices_crd.yaml
Labels: approved, size/XXL, lgtm
