Repository IBM/ibm-healthcheck-operator, pull requests merged in 2021-04, with the labels that each got.

#118 Fix rbac wildchar issue for 3.6 eus
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.2/ibm-healthcheck-operator.v3.8.2.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#117 Eliminating the use of wildchar for the rbac verbs
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/ibm-healthcheck-operator.v3.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#120 Change for system-healthcheck-service to 3.9.1 Task:45613
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.2/ibm-healthcheck-operator.v3.8.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: lgtm, size/XS

#119 Version change to 3.9.1 for system-healthcheck-service Task:45613
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/ibm-healthcheck-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: lgtm, size/XS

#122 bumpup operands version for 3.6 eus
  deploy/olm-catalog/ibm-healthcheck-operator/3.8.2/ibm-healthcheck-operator.v3.8.2.clusterserviceversion.yaml
Labels: size/XS

#121 Bumpup operands version for master
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/ibm-healthcheck-operator.v3.10.0.clusterserviceversion.yaml
Labels: size/XS

#124 Fix/openssl vulnerability to master
  deploy/operator.yaml
Labels: lgtm, size/XS

#123 Fix/openssl vulnerability 3.6eus
  deploy/operator.yaml
Labels: needs-rebase, size/XS

#125 updated OWNERS file to reflect team changes
  OWNERS
Labels: approved, size/S

#127 Removed deprecated node-selector label
  deploy/olm-catalog/ibm-healthcheck-operator/3.10.0/ibm-healthcheck-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
