Repository IBM/ibm-healthcheck-operator, pull requests merged in 2021-12, with the labels that each got.

#172 CSV for CS 3.15.0 Feb 2022 release
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/ibm-healthcheck-operator.v3.16.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#173 Removed CodeCov
  Makefile
  common/scripts/codecov.sh
Labels: approved, size/L, lgtm

#175 Adding restricted scc in csv file explictly
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/ibm-healthcheck-operator.v3.16.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#176 Adding SCC rule in role.yaml for all the cluster roles
  deploy/role.yaml
Labels: approved, lgtm, size/S
