Repository IBM/ibm-healthcheck-operator, pull requests merged in 2022-01, with the labels that each got.

#178 upgrading go version to 1.17.5
  go.mod
Labels: approved, size/M

#177 Update for lint error CS3.15.0
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/ibm-healthcheck-operator.v3.16.0.clusterserviceversion.yaml
Labels: approved, size/XS

#180 Fix for prjk issues
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/ibm-healthcheck-operator.v3.16.0.clusterserviceversion.yaml
  pkg/controller/healthservice/healthservice.go
  pkg/controller/healthservice/memcached.go
  pkg/controller/mustgatherservice/mustgatherservice.go
Labels: approved, size/S

#182 Upgrade Crypto module
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#183 Removed CSVDefinesCRDWithLicenseParameter rule for 3.15.0 release
  deploy/olm-catalog/ibm-healthcheck-operator/3.16.0/ibm-healthcheck-operator.v3.16.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
