Repository IBM/ibm-healthcheck-operator, pull requests merged in 2022-09, with the labels that each got.

#209 CD 3.21.0 Operands version bump up
  deploy/olm-catalog/ibm-healthcheck-operator/3.22.0/ibm-healthcheck-operator.v3.22.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#210 LTSR version bumpup
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/ibm-healthcheck-operator.v3.20.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/XXL, lgtm

#211 Version change for ltsr
  README.md
  version/version.go
Labels: approved, lgtm, size/XS

#212 Operand updates for ltsr
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/ibm-healthcheck-operator.v3.20.4.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#213 Update operand version for ltsr
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.4/ibm-healthcheck-operator.v3.20.4.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#214 operator version bump for 3.22
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/ibm-healthcheck-operator.v3.23.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL
