Repository IBM/ibm-healthcheck-operator, pull requests merged in 2022-11, with the labels that each got.

#217 LTSR 3.19.7 version bump up
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/ibm-healthcheck-operator.v3.20.6.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#218 Operand versions update
  deploy/olm-catalog/ibm-healthcheck-operator/3.23.0/ibm-healthcheck-operator.v3.23.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#219 New prow cluster name
  common/Makefile.common.mk
Labels: approved, size/XS

#220 New prow cluster name
  common/Makefile.common.mk
Labels: approved, size/XS

#221 Operands Version bump up for 1.3.17
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.6/ibm-healthcheck-operator.v3.20.6.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S
