Repository IBM/ibm-healthcheck-operator, pull requests merged in 2023-01, with the labels that each got.

#223 Version update for 3.23 CD release
  deploy/olm-catalog/ibm-healthcheck-operator/3.24.0/ibm-healthcheck-operator.v3.24.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#224 Dummy change to trigger new build for updating go version
  OWNERS
Labels: approved, lgtm, size/XS

#225 Version update for 3.19.8
  README.md
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/clusterhealth.ibm.com_clusterservicestatuses_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/ibm-healthcheck-operator.v3.20.7.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/operator.ibm.com_healthservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/operator.ibm.com_mustgatherconfigs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/operator.ibm.com_mustgatherjobs_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/operator.ibm.com_mustgatherservices_crd.yaml
  deploy/olm-catalog/ibm-healthcheck-operator/ibm-healthcheck-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL, lgtm

#226 Health check version issue fix
  deploy/olm-catalog/ibm-healthcheck-operator/3.20.7/ibm-healthcheck-operator.v3.20.7.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
